[workspace]
resolver = "2"
members = ["crates/editor", "crates/sticky"]
default-members = ["crates/sticky"]

[workspace.package]
publish = false
edition = "2024"

[workspace.dependencies]
gpui = { git = "https://github.com/huacnlee/zed.git", branch = "webview" }
gpui-component = { git = "https://github.com/longbridge/gpui-component.git" }
libsqlite3-sys = { version = "0.31.0" }

editor = { path = "crates/editor" }
