[workspace]
members = ["crates/sticky"]
default-members = ["crates/sticky"]

[workspace.package]
publish = false
edition = "2021"

[workspace.dependencies]

gpui = { git = "https://github.com/zed-industries/zed" }
