[workspace]
resolver = "2"
members = ["crates/sticky"]
default-members = ["crates/sticky"]

[workspace.package]
publish = false
edition = "2024"

[workspace.dependencies]
gpui = { git = "https://github.com/zed-industries/zed" }
libsqlite3-sys = { version = "0.31.0" }
