[workspace]
resolver = "2"
members = [
  "crates/adapter",
  "crates/db",
  "crates/editor",
  "crates/registry",
  "crates/sticky",
]
default-members = ["crates/sticky"]

[workspace.package]
publish = false
edition = "2024"

[workspace.dependencies]
gpui = { git = "https://github.com/huacnlee/zed.git", branch = "webview" }
gpui-component = { git = "https://github.com/longbridge/gpui-component.git" }
rusqlite = { version = "0.34.0", features = ["bundled"] }
ulid = { version = "1.2.1" }
anyhow = "1.0.97"

editor = { path = "crates/editor" }
db = { path = "crates/db" }
registry = { path = "crates/registry" }
adapter = { path = "crates/adapter" }
