[package]
name = "components"
version = "0.1.0"
publish.workspace = true
edition.workspace = true

[dependencies]
gpui = { workspace = true }
unicode-segmentation = { workspace = true }
smallvec = { workspace = true }
regex = { workspace = true }
