[package]
name = "adapter"
version = "0.1.0"
publish.workspace = true
edition.workspace = true

[dependencies]
rusqlite = { workspace = true }
derive-new = { workspace = true }
kernel = { workspace = true }
db = { workspace = true }
