[package]
name = "registry"
version = "0.1.0"
publish.workspace = true
edition.workspace = true

[dependencies]
rusqlite = { workspace = true }
adapter = { workspace = true }
kernel = { workspace = true }
