[package]
name = "registry"
version = "0.1.0"
publish.workspace = true
edition.workspace = true

[dependencies]
gpui = { workspace = true }
rusqlite = { workspace = true }
adapter = { workspace = true }
kernel = { workspace = true }
handler = { workspace = true }
