[package]
name = "window"
version = "0.1.0"
publish.workspace = true
edition.workspace = true

[dependencies]
gpui = { workspace = true }
registry = { workspace = true }
components = { workspace = true }
kernel = {workspace = true}
