[package]
name = "sticky"
version = "0.1.0"
edition = { workspace = true }

[[bin]]
name = "sticky"
path = "src/main.rs"

[dependencies]
libsqlite3-sys = { workspace = true }
gpui = { workspace = true }
