[package]
name = "sticky"
version = "0.1.0"
edition = { workspace = true }

[[bin]]
name = "sticky"
path = "src/main.rs"

[dependencies]
gpui = { workspace = true }
gpui-component = { workspace = true }
editor = { workspace = true }
db = { workspace = true }
