[package]
name = "editor"
version = "0.1.0"
publish.workspace = true
edition.workspace = true

[lib]
path = "src/editor.rs"

[dependencies]
gpui = { workspace = true }
gpui-component = { workspace = true }
